kui-shell/KuiClientTemplate

package-lock.json
package.json
plugins/plugin-kubeui/src/controller/kubectl/raw.ts

fix: enhance webpack build

---

README.md

fix: update README to improve webpack directions

---

package-lock.json
package.json
plugins/plugin-kubeui/package.json
plugins/plugin-kubeui/src/controller/command-prefix.ts
plugins/plugin-kubeui/src/controller/kubectl/catchall.ts
plugins/plugin-kubeui/src/controller/kubectl/contexts.ts
plugins/plugin-kubeui/src/controller/kubectl/create.ts
plugins/plugin-kubeui/src/controller/kubectl/delete.ts
plugins/plugin-kubeui/src/controller/kubectl/exec.ts
plugins/plugin-kubeui/src/controller/kubectl/get.ts
plugins/plugin-kubeui/src/controller/kubectl/raw.ts
plugins/plugin-kubeui/src/controller/kubectl/status.ts
theme/css/themes/tomorrow-night.css

this also:
- updates to the latest kui 5.2.5
- small refactoring to place the "kubeui" prefix in a common place
- update tomorrow-night theme to match latest kui master
Fixes #10

fix: catchall should send commands through PTY

---

plugins/plugin-kubeui/src/controller/kubectl/logs.ts
plugins/plugin-kubeui/src/test/k8s2/logs.ts

fix: `k logs` doesn't take label selector correctly

---

lerna.json
plugins/plugin-kubeui/package.json

correct lerna.json version

---

bin/amend-dist-for-krew.sh
bin/krew/darwin/kubectl-kubeui.sh
bin/krew/linux/kubectl-kubeui.sh
kubeui.yaml

fix: krew manifest has wrong bin

---

lerna.json
plugins/plugin-kubeui/package.json
plugins/plugin-kubeui/src/lib/view/modes/last-applied.ts
plugins/plugin-kubeui/src/preload.ts

clean up last applied mode code

---

theme/theme.json

fix: CSP violations

---

plugins/plugin-kubeui/src/index.ts
plugins/plugin-kubeui/src/lib/model/resource.ts

feat(plugins/plugin-kubeui): add isPod and isDeployment APIs

---

plugins/plugin-kubeui/src/index.ts
plugins/plugin-kubeui/src/lib/model/resource.ts

feat(plugins/plugin-kubeui): add Job and isJob impl

---

plugins/plugin-kubeui/src/index.ts

feat(plugins/plugin-kubeui): export doExec*

---

plugins/plugin-kubeui/src/controller/kubectl/raw.ts
plugins/plugin-kubeui/src/index.ts

feat(plugins/plugin-kubeui): expose doExecRaw

---

plugins/plugin-kubeui/i18n/resources_en_US.json
plugins/plugin-kubeui/src/lib/model/resource.ts
plugins/plugin-kubeui/src/lib/util/name.ts
plugins/plugin-kubeui/src/lib/view/modes/involved-object.ts
plugins/plugin-kubeui/src/preload.ts
plugins/plugin-kubeui/src/test/k8s2/events.ts

see #56 for the two enhancements
Fixes #56

feat(plugins/plugin-kubeui): enhance events display

---

package.json

fix: build:krew uses undefined build target

---

README.md

doc: prebuilt image -> prebuilt images

---

README.md

doc: clarify screenshot and kui discussions

---

plugins/plugin-kubeui/src/controller/kubectl/apiVersion.ts
plugins/plugin-kubeui/src/controller/kubectl/get.ts
plugins/plugin-kubeui/src/controller/kubectl/logs.ts
plugins/plugin-kubeui/src/controller/kubectl/options.ts
plugins/plugin-kubeui/src/controller/kubectl/status.ts
plugins/plugin-kubeui/src/index.ts
plugins/plugin-kubeui/src/lib/model/resource.ts
plugins/plugin-kubeui/src/lib/view/modes/crud.ts
plugins/plugin-kubeui/src/lib/view/modes/events.ts
plugins/plugin-kubeui/src/lib/view/modes/involved-object.ts
plugins/plugin-kubeui/src/lib/view/modes/summary.ts

fix(plugins/plugin-kubeui): improve Summary and InvolvedObject handling

---

package.json

Reverts kui-shell/plugin-kubeui#106

Revert "bump to 0.1.1"

---

.travis.yml
package-lock.json
package.json
plugins/plugin-helmui/src/controller/helm/catchall.ts
plugins/plugin-helmui/src/controller/helm/get.ts
plugins/plugin-helmui/src/controller/helm/help.ts
plugins/plugin-helmui/src/controller/helm/history.ts
plugins/plugin-helmui/src/controller/helm/install.ts
plugins/plugin-helmui/src/controller/helm/repo.ts
plugins/plugin-helmui/src/controller/helm/search.ts
plugins/plugin-helmui/src/controller/helm/status.ts
plugins/plugin-helmui/src/plugin.ts
plugins/plugin-helmui/src/test/helm/helm-repo-add-and-search.ts
plugins/plugin-helmui/src/test/helm/helm.ts
plugins/plugin-kubeui/src/controller/kubectl/exec.ts
plugins/plugin-kubeui/src/controller/kubectl/options.ts
plugins/plugin-kubeui/src/controller/kubectl/raw.ts
plugins/plugin-kubeui/src/index.ts

fix: add helmui tests

---

package.json

fix: specify minimum engine preqreqs for nodejs and npm

---

package.json

fix: windows builds require wine64 in linux

---

package.json

fix: improved apt-get install of wine64

---

package.json

fix: apt-get update for travis install of wine64

---

package.json

fix: missing sudo in apt-get install wine64

---

package.json

fix: more attempts at getting wine in travis

---

package.json

chore: bump to 0.1.4

---

.travis.yml

chore: use node12 in travis

---

package.json

chore: bump to 0.1.6

---

plugins/plugin-kubeui/src/controller/kubectl/status.ts
plugins/plugin-kubeui/src/test/k8s1/status.ts

fix(plugins/plugin-kubeui): k status --all gives bad error output

---

.travis.yml
plugins/plugin-kubeui/src/controller/kubectl/get.ts
plugins/plugin-kubeui/src/controller/kubectl/top.ts
plugins/plugin-kubeui/src/lib/view/formatTable.ts
plugins/plugin-kubeui/src/plugin.ts
plugins/plugin-kubeui/src/test/k8s2/top.ts

feat(plugins/plugin-kubeui): kubectl top support

---

plugins/plugin-kubeui/src/controller/kubectl/get.ts
plugins/plugin-kubeui/src/lib/model/resource.ts
plugins/plugin-kubeui/src/lib/view/modes/summary.ts
plugins/plugin-kubeui/src/test/k8s2/get-pod.ts

previously, we were displaying this as raw yaml in the repl
Fixes #173

fix(plugins/plugin-kubeui): get list-as-yaml improvements

---

package.json

chore: bump to 0.1.8

---

package.json

chore: update release-it config to publish to npm

---

.travis.yml

fix: add npm token for npm release stage

---

.travis.yml
package.json

chore: back out npm auth and publish bits

---

plugins/plugin-kubeui/src/lib/view/modes/conditions.ts
plugins/plugin-kubeui/src/non-headless-preload.ts

feat(plugins/plugin-kubeui): restore conditions tab

---

package-lock.json
package.json
plugins/plugin-kubeui/src/index.ts
plugins/plugin-kubeui/src/lib/model/resource.ts
plugins/plugin-tekton/CHANGELOG.md
plugins/plugin-tekton/package.json
plugins/plugin-tekton/samples/@demos/tekton/pipeline.yaml
plugins/plugin-tekton/samples/@demos/tekton/pipeline2.yaml
plugins/plugin-tekton/samples/@demos/tekton/simple.yaml
plugins/plugin-tekton/src/controller/get/options.ts
plugins/plugin-tekton/src/controller/get/step.ts
plugins/plugin-tekton/src/controller/get/task.ts
plugins/plugin-tekton/src/controller/preview.ts
plugins/plugin-tekton/src/index.ts
plugins/plugin-tekton/src/lib/read.ts
plugins/plugin-tekton/src/lib/success.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts
plugins/plugin-tekton/src/model/fetch.ts
plugins/plugin-tekton/src/model/modes/flow.ts
plugins/plugin-tekton/src/model/modes/logs.ts
plugins/plugin-tekton/src/model/modes/run.ts
plugins/plugin-tekton/src/model/modes/trace.ts
plugins/plugin-tekton/src/model/resource.ts
plugins/plugin-tekton/src/plugin.ts
plugins/plugin-tekton/src/preload.ts
plugins/plugin-tekton/src/view/flow.ts
plugins/plugin-tekton/tsconfig-es6.json
plugins/plugin-tekton/tsconfig.json
tsconfig-es6.json
tsconfig.json

feat: incorporate plugin-tekton

---

package-lock.json
package.json
plugins/plugin-kubeui/src/controller/kubectl/delete.ts
plugins/plugin-kubeui/src/controller/kubectl/describe.ts
plugins/plugin-kubeui/src/controller/kubectl/exec.ts
plugins/plugin-kubeui/src/controller/kubectl/get.ts
plugins/plugin-kubeui/src/controller/kubectl/run.ts
plugins/plugin-kubeui/src/index.ts
plugins/plugin-openshift/package.json
plugins/plugin-openshift/src/controller/exec.ts
plugins/plugin-openshift/src/controller/kubectl/delegates.ts
plugins/plugin-openshift/src/controller/raw.ts
plugins/plugin-openshift/src/plugin.ts
plugins/plugin-openshift/tsconfig-es6.json
plugins/plugin-openshift/tsconfig.json
tsconfig-es6.json
tsconfig.json

for those commands that directly delegate to kubectl; e.g. get, create, apply, delete, describe, run
Fixes #199

feat: provide basic oc support

---

lerna.json
package-lock.json
package.json
plugins/plugin-helmui/package.json
plugins/plugin-ibmcloud/package.json
plugins/plugin-kubeui/package.json
plugins/plugin-logui/package.json
plugins/plugin-openshift/package.json
plugins/plugin-operator-framework/package.json
plugins/plugin-tekton/package.json

chore: bump lerna.json version to match the rest

---

.travis.yml
plugins/plugin-logui/src/controller/kubectl/logs.ts
plugins/plugin-logui/src/modes/show-logs.ts

fix(plugins/plugin-logui): show logs versus browsers

---

plugins/plugin-logui/src/controller/kubectl/logs.ts

fix(plugins/plugin-kubeui): introduce default --since for logs -f

---

.travis.yml

chore: use lerna.json version for release-it version

---

package.json

Reverts kui-shell/plugin-kubeui#216

Revert "disable release notes until we can figure things out"

---

.travis.yml

Reverts kui-shell/plugin-kubeui#214

Revert "chore: use lerna.json version for release-it version"

---

plugins/plugin-client/package.json

fix(plugins/plugin-client): set private:true

---

.travis.yml
package.json

chore: use auto-changelog for release-it

---

.travis.yml

chore: stop using travis for release-it (for now)

---

plugins/plugin-view-utilization/i18n/widgets_en_US.json
plugins/plugin-view-utilization/src/lib/widgets/cluster-utilization.ts

fix(Plugins/plugin-view-utilization): add tooltips to utilization widget

---

package.json

fix: update to new location of release-it changelog template

---

plugins/plugin-kubeui/src/test/k8s2/events.ts
plugins/plugin-kubeui/src/test/k8s2/kubectl-exec.ts

fix(plugins/plugin-kubeui): two events test bugs

---

package-lock.json
package.json
plugins/plugin-kubeui/src/controller/kubectl/options.ts
plugins/plugin-kubeui/src/index.ts
plugins/plugin-kubeui/src/lib/model/resource.ts
plugins/plugin-view-utilization/README.md
plugins/plugin-view-utilization/i18n/table_en_US.json
plugins/plugin-view-utilization/src/controller/get-node-data.ts
plugins/plugin-view-utilization/src/controller/get-pod-data.ts
plugins/plugin-view-utilization/src/controller/utilization/cluster.ts
plugins/plugin-view-utilization/src/controller/utilization/node.ts
plugins/plugin-view-utilization/src/lib/parse.ts
plugins/plugin-view-utilization/src/plugin.ts
plugins/plugin-view-utilization/src/view/bar.ts
plugins/plugin-view-utilization/src/view/slash.ts
plugins/plugin-view-utilization/src/view/widgets/cluster-utilization.ts

fix: refine cluster utilization metrics

---

plugins/plugin-kubeui/src/controller/kubectl/watch/get-watch.ts
plugins/plugin-kubeui/src/test/k8s1/apply-pod.ts
plugins/plugin-kubeui/src/test/k8s2/watch-error-handling.ts
plugins/plugin-kubeui/tests/lib/k8s/utils.js

fix(plugins/plugin-kubeui): get --watch tables can stick yellow

---

plugins/plugin-view-utilization/i18n/table_en_US.json
plugins/plugin-view-utilization/src/controller/get-pod-data.ts

fix(plugins/plugin-view-utilization): kubectl top errors when no pods

---

plugins/plugin-helmui/package.json
plugins/plugin-ibmcloud/package.json
plugins/plugin-logui/package.json
plugins/plugin-openshift/package.json
plugins/plugin-operator-framework/package.json
plugins/plugin-tekton/package.json
plugins/plugin-view-utilization/package.json

fix: some plugins missed specifying dependency of plugin-kubeui

---

plugins/plugin-helmui/package.json
plugins/plugin-ibmcloud/package.json
plugins/plugin-logui/package.json
plugins/plugin-tekton/package.json
plugins/plugin-view-utilization/package.json

fix: restore "*" kubeui deps

---

package-lock.json
plugins/plugin-kubeui/src/lib/model/resource.ts

fix: open package.json results in error

---

plugins/plugin-kubeui/i18n/resources_en_US.json
plugins/plugin-kubeui/src/controller/kubectl/fqn.ts
plugins/plugin-kubeui/src/lib/model/resource.ts
plugins/plugin-kubeui/src/lib/view/modes/crd-summary.ts
plugins/plugin-kubeui/src/lib/view/modes/events.ts
plugins/plugin-kubeui/src/lib/view/modes/show-crd-managed-resources.ts
plugins/plugin-kubeui/src/non-headless-preload.ts

feat: improve sidecar presentation of CRDs

---

plugins/plugin-tekton/i18n/modes_en_US.json
plugins/plugin-tekton/src/model/modes/flow.ts
plugins/plugin-tekton/src/model/modes/logs.ts
plugins/plugin-tekton/src/model/modes/trace.ts

fix(plugins/plugin-tekton): tekton tab labels should be uppercase

---

plugins/plugin-tekton/src/preload.ts

fix(plugins/plugin-tekton): tekton preload failure in production builds

---

plugins/plugin-kubeui/src/controller/kubectl/fqn.ts
plugins/plugin-kubeui/src/lib/view/modes/show-crd-managed-resources.ts

fix(plugins/plugin-kubeui): k get crd can fail for certain crds

---

plugins/plugin-kubeui/src/lib/view/modes/crd-summary.ts

fix(plugins/plugin-kubeui): improve safety of crd-summary code

---

README.md

docs: update download links on main README.md page

---

plugins/plugin-helmui/src/controller/helm/get.ts
plugins/plugin-kubeui/src/controller/kubectl/contexts.ts
plugins/plugin-kubeui/src/controller/kubectl/get.ts
plugins/plugin-kubeui/src/lib/model/resource.ts
plugins/plugin-logui/src/models/resource.ts
plugins/plugin-tekton/src/lib/tekton2graph.ts

fix: tag kubeResource to help distinguish kubeResource from open-ended structure response

---

plugins/plugin-kubeui/src/controller/kubectl/options.ts
plugins/plugin-kubeui/src/lib/util/help.ts

feat: render Table for `kubectl options` and incorporate this in `kubectl` usage

---

plugins/plugin-kubeui/src/controller/kubectl/api-resources.ts
plugins/plugin-kubeui/src/plugin.ts
plugins/plugin-kubeui/src/test/k8s2/api-resources.ts

fix: kubectl api-resources is not presented as a kui table

---

bin/kubectl-kui
plugins/plugin-kubeui-client/config.d/exec.json

fix: incorrect defaultContext in client config

---

bin/amend-dist-for-krew.sh
bin/krew/Kui-darwin-x64/kubectl-kui
bin/krew/Kui-linux-x64/kubectl-kui
bin/krew/darwin/kubectl-kubeui.sh
bin/krew/linux/kubectl-kubeui.sh

fix: restore kubectl plugin capability

---

README.md
bin/amend-dist-for-krew.sh

doc: update README.md to document kubectl plugin setup

---

bin/amend-dist-for-krew.sh

fix: krew build on linux

---

plugins/plugin-kubeui/src/controller/kubectl/fqn.ts
plugins/plugin-kubeui/src/controller/kubectl/status.ts
plugins/plugin-kubeui/src/lib/view/modes/button.ts
plugins/plugin-kubeui/src/lib/view/modes/involved-object.ts
plugins/plugin-kubeui/src/lib/view/modes/show-crd-managed-resources.ts
plugins/plugin-kubeui/src/lib/view/modes/summary.ts
plugins/plugin-kubeui/src/test/k8s1/apply-crd.ts
plugins/plugin-kubeui/tests/data/k8s/crd.yaml

fix: some underlying kubectl get commands are not disambiguating resources with the same kind

---

.travis.yml
plugins/plugin-kubeui/src/test/k8s1/apply-crd.ts
plugins/plugin-kubeui/src/test/k8s1/create-pod.ts
plugins/plugin-kubeui/src/test/k8s1/describe.ts
plugins/plugin-kubeui/src/test/k8s1/edit.ts
plugins/plugin-kubeui/src/test/k8s2/events.ts
plugins/plugin-kubeui/src/test/k8s2/get-pod.ts
plugins/plugin-kubeui/tests/lib/k8s/utils.d.ts
plugins/plugin-kubeui/tests/lib/k8s/utils.js
tools/travis/microk8s.sh

test: add tests for oc

---

plugins/plugin-kubeui/src/controller/kubectl/fqn.ts
plugins/plugin-kubeui/src/controller/kubectl/status.ts
plugins/plugin-kubeui/src/test/k8s1/apply-crd.ts

fix: apiVersion is used incorrectly when feching resources

---

plugins/plugin-helmui/i18n/resources_en_US.json
plugins/plugin-helmui/src/controller/helm/status.ts
plugins/plugin-helmui/src/test/helm/helm.ts
plugins/plugin-kubeui/i18n/resources_en_US.json

feat: improve helm status formatting using NavResponse

---

plugins/plugin-kubeui/src/controller/kubectl/describe.ts
plugins/plugin-kubeui/src/test/k8s1/describe.ts

fix: oc describe fails

---

plugins/plugin-kubeui/src/controller/kubectl/describe.ts
plugins/plugin-kubeui/src/controller/kubectl/exec.ts
plugins/plugin-kubeui/src/lib/util/util.ts
plugins/plugin-kubeui/src/test/k8s1/describe.ts

fix: kubectl(oc) describe (--help) command fails

---

.travis.yml
plugins/plugin-kubeui/src/test/k8s1/redirects.ts
plugins/plugin-logui/src/controller/kubectl/logs.ts
plugins/plugin-logui/src/index.ts
plugins/plugin-logui/src/test/logs/logs-dash-f.ts
plugins/plugin-logui/src/test/logs/logs.ts
plugins/plugin-openshift/package.json
plugins/plugin-openshift/src/controller/kubectl/delegates.ts

fix: delegate `oc logs` to logui
